/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedComunicadosRouteImport } from './routes/_authenticated/comunicados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIncidenciasRouteImport } from './routes/_authenticated/incidencias'
import { Route as AuthenticatedTurnosRouteImport } from './routes/_authenticated/turnos'
import { Route as AuthenticatedVipRouteImport } from './routes/_authenticated/vip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComunicadosRoute =
  AuthenticatedComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidenciasRoute =
  AuthenticatedIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTurnosRoute = AuthenticatedTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVipRoute = AuthenticatedVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/vip': typeof AuthenticatedVipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/vip': typeof AuthenticatedVipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/comunicados': typeof AuthenticatedComunicadosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/incidencias': typeof AuthenticatedIncidenciasRoute
  '/_authenticated/turnos': typeof AuthenticatedTurnosRoute
  '/_authenticated/vip': typeof AuthenticatedVipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/comunicados'
    | '/dashboard'
    | '/incidencias'
    | '/turnos'
    | '/vip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/comunicados'
    | '/dashboard'
    | '/incidencias'
    | '/turnos'
    | '/vip'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/comunicados'
    | '/_authenticated/dashboard'
    | '/_authenticated/incidencias'
    | '/_authenticated/turnos'
    | '/_authenticated/vip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comunicados': {
      id: '/_authenticated/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof AuthenticatedComunicadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidencias': {
      id: '/_authenticated/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof AuthenticatedIncidenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turnos': {
      id: '/_authenticated/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof AuthenticatedTurnosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip': {
      id: '/_authenticated/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof AuthenticatedVipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComunicadosRoute: typeof AuthenticatedComunicadosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIncidenciasRoute: typeof AuthenticatedIncidenciasRoute
  AuthenticatedTurnosRoute: typeof AuthenticatedTurnosRoute
  AuthenticatedVipRoute: typeof AuthenticatedVipRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComunicadosRoute: AuthenticatedComunicadosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIncidenciasRoute: AuthenticatedIncidenciasRoute,
  AuthenticatedTurnosRoute: AuthenticatedTurnosRoute,
  AuthenticatedVipRoute: AuthenticatedVipRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
